<a href="https://colab.research.google.com/github/DhanyaShreeKP/DSC-assignments/blob/master/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [ ]:
# Create a 1-dimensional NumPy array using np.array()
a=np.array([1,3,4,5])
print(a)


# Create a 2-dimensional NumPy array using np.array()
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
  

[1 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
a.shape,a.ndim,a.dtype,a.itemsize



((4,), 1, dtype('int64'), 8)

In [ ]:
# Attributes of 2-dimensional array
b.shape,b.ndim,b.dtype,b.itemsize

((2, 4), 2, dtype('int64'), 8)

In [ ]:
# Create an array of shape (5, 5) with only ones
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Create an array of shape (3, 3, 5) with only zeros
np.zeros((3,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10,size=((7,2)))


array([[3, 6],
       [0, 1],
       [3, 3],
       [8, 7],
       [9, 9],
       [2, 8],
       [5, 9]])

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3,5)


array([[0.67642119, 0.72020544, 0.61145069, 0.68766835, 0.78914481],
       [0.76384706, 0.72455223, 0.38450784, 0.44636396, 0.73285977],
       [0.60905578, 0.38751762, 0.33081484, 0.1039742 , 0.7277712 ]])

In [ ]:
# Create an array of normally distributed random numbers
np.random.randint(99,size=((5,6)))

array([[82, 56, 56,  4, 63, 38],
       [95, 93, 82, 40, 41, 73],
       [86,  2, 68, 93,  0, 57],
       [92, 29, 34, 83, 48, 57],
       [54, 59, 12, 84, 22, 28]])

In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
c=np.random.randint(10,size=((4,6)))
print(c)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [ ]:
# Copy the code from the cell above and run it again
d=c
print(d)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [ ]:
# Find the 0'th index of the latest array you created
d[0,0]

6

In [ ]:
# Get the first 2 rows of latest array you created
d[0,:],d[1,:]

(array([6, 3, 7, 4, 6, 9]), array([2, 6, 7, 4, 3, 7]))

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
d[0,:2],d[1,:2]

(array([6, 3]), array([2, 6]))

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
g=np.random.randint(25,size=(3,5))
print(g)
h=np.ones((3,5))
print(h)

[[11  7 14  2 13]
 [16  3 17  7  3]
 [ 1  5 21  9  3]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Add the two arrays together
g+h

array([[12.,  8., 15.,  3., 14.],
       [17.,  4., 18.,  8.,  4.],
       [ 2.,  6., 22., 10.,  4.]])

In [ ]:
# Create another array of ones of shape (5, 3)
i=np.ones((5,3))
print(i)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
g+h

array([[12.,  8., 15.,  3., 14.],
       [17.,  4., 18.,  8.,  4.],
       [ 2.,  6., 22., 10.,  4.]])

In [ ]:
# Do the same operation you just did but this time with a transpose on one array
h.T
j=g+h
print(j)

[[12.  8. 15.  3. 14.]
 [17.  4. 18.  8.  4.]
 [ 2.  6. 22. 10.  4.]]


In [ ]:
# Take the latest array to the power of 2 using the python way
np.exp(j)

array([[1.62754791e+05, 2.98095799e+03, 3.26901737e+06, 2.00855369e+01,
        1.20260428e+06],
       [2.41549528e+07, 5.45981500e+01, 6.56599691e+07, 2.98095799e+03,
        5.45981500e+01],
       [7.38905610e+00, 4.03428793e+02, 3.58491285e+09, 2.20264658e+04,
        5.45981500e+01]])

In [ ]:
# Do the same thing with numpy way
j ** 2

array([[144.,  64., 225.,   9., 196.],
       [289.,  16., 324.,  64.,  16.],
       [  4.,  36., 484., 100.,  16.]])

In [ ]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(j),np.min(j),np.max(j),np.std(j),np.var(j)


(9.8, 2.0, 22.0, 6.035450825470013, 36.42666666666666)

In [ ]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
a1=np.random.randint(10,size=((3,3)))
a2=np.random.randint(10,size=((3,2)))

In [ ]:
# Perform a dot product on the two newest arrays you created
np.hstack([a1,a2])

array([[5, 1, 9, 7, 4],
       [1, 9, 3, 1, 4],
       [7, 6, 8, 7, 9]])

In [ ]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
m=np.random.randint(10,size=((4,3)))
n=np.random.randint(10,size=((4,3)))

In [ ]:
# Perform a hadamard product on the two newest arrays you created
m*n

array([[24,  0,  4],
       [ 8, 32, 63],
       [ 0, 36,  4],
       [ 0, 21,  4]])

In [ ]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(a1,a2)

array([[ 99, 105],
       [ 37,  67],
       [111, 124]])

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
a1.T
a2.T
np.dot(a1,a2)

array([[ 99, 105],
       [ 37,  67],
       [111, 124]])

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
x=np.random.randint(10,size=((3,3)))
y=np.random.randint(10,size=((3,3)))
print(x)

[[0 7 2]
 [6 1 1]
 [6 5 2]]


In [ ]:
# Compare the two arrays with '>', '<=' and '==' 
x>y,x<=y,x==y

(array([[False, False, False],
        [False, False, False],
        [ True,  True, False]]), array([[ True,  True,  True],
        [ True,  True,  True],
        [False, False,  True]]), array([[False, False, False],
        [False, False, False],
        [False, False, False]]))

In [ ]:
# Sort one of the arrays you just created in ascending order


In [ ]:
# Sort the indexes of one of the arrays you just created
np.argmax(x)

1

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(x,axis=0)

array([1, 0, 0])

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
random_array=np.random.randint(10,size=(1,100))
random_array

array([[0, 3, 3, 4, 6, 6, 3, 6, 2, 5, 1, 9, 8, 4, 5, 3, 9, 6, 8, 6, 0, 0,
        8, 8, 3, 8, 2, 6, 5, 7, 8, 4, 0, 2, 9, 7, 5, 7, 8, 3, 0, 0, 9, 3,
        6, 1, 2, 0, 4, 0, 7, 0, 0, 1, 1, 5, 6, 4, 0, 0, 2, 1, 4, 9, 5, 6,
        3, 6, 7, 0, 5, 7, 4, 3, 1, 5, 5, 0, 8, 5, 2, 3, 3, 2, 9, 2, 2, 3,
        6, 3, 8, 0, 7, 6, 1, 7, 0, 8, 8, 1]])

In [ ]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(random_array)

11

In [ ]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(random_array)

0